# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  TZ: "Asia/Taipei"
  USER_NAME: github-actions[bot]
  USER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
  DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
  Commit_MSG: ${{ github.event.head_commit.message }}
jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy Hexo Blog
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true # Checkout private submodules(themes or something else).

      - name: Timezone set Asia/Taipei
        run: sudo timedatectl set-timezone 'Asia/Taipei'
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup pnpm with npm
        run: |
          npm install -g pnpm@7.5.0
          pnpm -v

      - name: Cache pnpm store
        uses: actions/cache@v4
        id: cache
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install Dependencies
        run: |
          echo "Installing dependencies with pnpm..."
          pnpm install --no-frozen-lockfile || pnpm install --no-frozen-lockfile
          
      - name: Hexo Generate
        run: |
          pnpm hexo clean
          pnpm hexo generate

      - name: Hexo Deploy
        id: deploy
        uses: marsen/hexo-action@v1.0.7
        with:
          deploy_key: ${{ env.DEPLOY_KEY }}
          user_email: ${{ env.USER_EMAIL }}
          commit_msg: ${{ env.Commit_MSG }}